### ISSUE TITLE
ヘルパーをコントローラで明示的にincludeする理由を確認する

### ISSUE THREAD

**Issue by norotime** [niceblow/SkyPost#15]
https://github.com/niceblow/SkyPost/blob/2bf90186380dffd10b02bd3b859c5c340a36fafd/app/controllers/blogs_controller.rb#L2

**Comment by niceblow** [comment]
上記includeは、isshue#2（コントローラ内にはCRUD処理以外は極力書かないようにする）の対応時に追記したものとなりますが、対応に何か不足があったと言うことでしょうか。もう少し補足いただけると助かります。よろしくお願いします。

**Comment by norotime** [comment]
@niceblow ヘルパーのメソッドは「ビューの表示(≒HTMLの組立)に必要なロジックのセット」です。コントローラでインクルードして使うことに違和感があります。ヘルパーは、View上であれば、何も明示しなくても使えます。

>コントローラ内にはCRUD処理以外は極力書かないようにする）の対応

これは、モデルに記述するなど違う方法で検討してください。

**Comment by norotime** [comment]
@niceblow やむを得ない場合のみ、ヘルパーに記述する方法が良いでしょう。

**Comment by norotime** [comment]
これらでは足りないものをheplersに記述します。
https://railsguides.jp/action_view_overview.html#action-view%E3%81%8C%E6%8F%90%E4%BE%9B%E3%81%99%E3%82%8B%E3%83%98%E3%83%AB%E3%83%91%E3%83%BC%E3%81%AE%E6%A6%82%E8%A6%81

**Comment by niceblow** [comment]
該当のログインチェック機能は、下記カリキュラムのヒントを元に課題作成した際の
before_actionの機能を参考としていましたが、ログインチェックのメソッドをモデルに記述する形で、
blogs_controllerのbefore_actionが効くように構成変更させるという認識でよろしいですか？

（参考カリキュラム）
ログインシステムシリーズ課題【ログイン機能作成】
〜
ログインしていなければ特定のアクションに行けない仕様（ヒント）
current_userが存在していなければ、強制的にログイン画面にリダイレクトさせるというメソッドを定義する。
定義したメソッドをblogs_controllerのbefore_actionとして使用し、
onlyオプションでnew,edit,showアクションを指定する。
-----

**Comment by niceblow** [comment]
application_controller.rb で既にincludeされているsessions_helper.rbに
current_userやログイン確認のメソッドが記述されていますので、
機能的にこちらに追記したら違和感がないような気もしますが、この案はいかがでしょうか。

**Comment by niceblow** [comment]
blogs_controller.rbのinclude ApplicationHelperは削除し、sessions_helper.rbに以下のように追記する方式です。
---
skyposts/app/helpers/sessions_helper.rb

module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
#以下追記
  def login_check
    redirect_to new_session_path if current_user.nil?
  end
#ここまで
end
---

**Comment by niceblow** [comment]
上記の全コントローラーの共通クラスに、ログインしてない場合は強制的にログイン画面に遷移する処理を追加する方式ではどうでしょうか。

**Comment by norotime** [comment]
@niceblow こちらの方式で進めてみましょう！
>上記の全コントローラーの共通クラスに、ログインしてない場合は強制的にログイン画面に遷移する処理を追加する方式ではどうでしょうか。

**Comment by niceblow** [comment]
ご返信ありがとうございます。上記方式にて修正いたしました。
